import '../styles/globals.css'
import type { AppProps } from 'next/app'
import Head from 'next/head'
import { ProductsProvider } from '../context/ProductsContext'
import { ChakraProvider, ColorModeScript, Container } from '@chakra-ui/react'
import { theme } from '../lib/theme'
import { FontProvider } from '../context/FontContext'
import { Footer, Navbar } from '../components'
import { Fonts } from '../lib/fonts'
import { AnimatePresence } from 'framer-motion'
import { AuthProvider } from '../context/AuthContext'
import { CartProvider } from '../context/CartContext'

function MyApp({ Component, pageProps, router }: AppProps) {
  return (
    <>
      <ChakraProvider theme={theme}>
        <Fonts/>
        <FontProvider>
          <AuthProvider>
            <ProductsProvider>
              <CartProvider>
                <Head>
                  <title>eShop</title>
                  <meta name="description" content="Generated by create next app" />
                  <link rel="icon" href="/favicon.ico" />
                </Head>

                <main>
                  <Navbar router={router} />
                  <AnimatePresence
                    exitBeforeEnter
                    initial={true}
                    onExitComplete={() => {
                      if (typeof window !== 'undefined') {
                        window.scrollTo({ top: 0 })
                      }
                    }}
                  >
                    <Component {...pageProps} key={router.route} />
                  </AnimatePresence>
                </main>

                <footer>
                  <Footer />
                </footer>
                </CartProvider>
            </ProductsProvider>
          </AuthProvider>
        </FontProvider>
      </ChakraProvider>
    </>
  )
}

export default MyApp
